import type { Metadata } from "next";

import LmbFooter from "../(components)/lmb-footer";
import LmbMainNavbar from "./(components)/lmb-main-navbar";

export const metadata: Metadata = {
  title: "LMB | Nos produits",
  description: "Generated by create next app",
};

export default function ProductLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="min-h-full flex flex-col">
      <LmbMainNavbar />
      {children}
      <LmbFooter />
    </div>
  );
}
